---
- name: Download Nginx signing key
  ansible.builtin.get_url:
    url: "{{ nginx_key_url }}"
    dest: "{{ nginx_key_tmp }}"
    mode: '0644'

- name: Convert Nginx key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o "{{ nginx_key_dest }}" "{{ nginx_key_tmp }}"
    creates: "{{ nginx_key_dest }}"

- name: Verify the downloaded Nginx key
  ansible.builtin.command:
    cmd: gpg --dry-run --quiet --no-keyring --import --import-options import-show "{{ nginx_key_dest }}"
  register: key_verification
  failed_when: "'573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62' not in key_verification.stdout"
  changed_when: false

- name: Add stable Nginx repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ nginx_key_dest }}] {{ nginx_repo_url_stable }}"
    state: present
    filename: nginx

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Clean up temporary signing key file
  ansible.builtin.file:
    path: "{{ nginx_key_tmp }}"
    state: absent

- name: Setup odoo configuration
  ansible.builtin.template:
    src: odoo.conf.j2
    dest: /etc/nginx/sites-available/odoo.conf
    owner: {{ sudo_user }}
    group: {{ erp_group }}
    mode: '0644'
  notify: Reload Nginx